<?xml version="1.0" encoding="utf-8"?><Database Name="StudentDB" Class="StudentDBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=LAPTOP-QUAMAIO7;Initial Catalog=StudentDB;Integrated Security=True;Trust Server Certificate=True" SettingsObjectName="Linq_to_Sql_CRUD_Winforms.Properties.Settings" SettingsPropertyName="StudentDBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Student" Member="Students">
    <Type Name="Student">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Standard" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.spShowStudents" Method="spShowStudents">
    <Parameter Name="standard" Type="System.Int32" DbType="Int" />
    <ElementType Name="spShowStudentsResult">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Gender" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Age" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Standard" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.InsertData" Method="InsertData">
    <Parameter Name="Name" Parameter="name" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Gender" Parameter="gender" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="Age" Parameter="age" Type="System.Int32" DbType="Int" />
    <Parameter Name="Standard" Parameter="standard" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
</Database>